/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;
import obj.Settings;

/**
 *
 * @author JuanMier
 */
public class PrePartida extends javax.swing.JFrame {
    
    private Settings opciones;
    private LauncherRF principal;

    /**
     * Creates new form PrePartida
     */
    private PrePartida() {
        initComponents();
    }
    
    public PrePartida(LauncherRF p) {
        this();
        principal = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpModo = new javax.swing.ButtonGroup();
        sldVertical = new javax.swing.JSlider();
        sldHorizontal = new javax.swing.JSlider();
        txtHorizontal = new javax.swing.JTextField();
        txtVertical = new javax.swing.JTextField();
        chkCustomSizes = new javax.swing.JCheckBox();
        bttExperimental = new javax.swing.JRadioButton();
        bttClásico = new javax.swing.JRadioButton();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SumaTres - Prepartida");
        setName("Prepartida"); // NOI18N
        setResizable(false);

        sldVertical.setMaximum(15);
        sldVertical.setMinimum(3);
        sldVertical.setOrientation(javax.swing.JSlider.VERTICAL);
        sldVertical.setValue(5);
        sldVertical.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerticalStateChanged(evt);
            }
        });

        sldHorizontal.setMaximum(15);
        sldHorizontal.setMinimum(3);
        sldHorizontal.setValue(5);
        sldHorizontal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldHorizontalChanged(evt);
            }
        });

        txtHorizontal.setEditable(false);
        txtHorizontal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHorizontal.setText("5");

        txtVertical.setEditable(false);
        txtVertical.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVertical.setText("5");
        txtVertical.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtVerticalComponentMoved(evt);
            }
        });

        chkCustomSizes.setText("Tamaño personalizado");
        chkCustomSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomSizesToggled(evt);
            }
        });

        grpModo.add(bttExperimental);
        bttExperimental.setText("Modo experimental");

        grpModo.add(bttClásico);
        bttClásico.setSelected(true);
        bttClásico.setText("Modo clásico");

        btnJugar.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(sldHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(sldVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCustomSizes)
                            .addComponent(bttClásico)
                            .addComponent(bttExperimental)
                            .addComponent(btnJugar))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnJugar)
                        .addGap(18, 18, 18)
                        .addComponent(bttClásico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttExperimental)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCustomSizes)
                        .addGap(6, 6, 6))
                    .addComponent(sldVertical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCustomSizesToggled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomSizesToggled
        txtHorizontal.setEditable(chkCustomSizes.isSelected());
        txtVertical.setEditable(chkCustomSizes.isSelected());
    }//GEN-LAST:event_chkCustomSizesToggled

    private void sldHorizontalChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldHorizontalChanged
        txtHorizontal.setText(String.format("%s", sldHorizontal.getValue()));
    }//GEN-LAST:event_sldHorizontalChanged

    private void sldVerticalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerticalStateChanged
        txtVertical.setText(String.format("%s", sldVertical.getValue()));
    }//GEN-LAST:event_sldVerticalStateChanged

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        opciones = new Settings(Integer.parseInt(txtHorizontal.getText()), Integer.parseInt(txtVertical.getText()), bttExperimental.isSelected());
        this.setVisible(false);
        if(principal == null) System.exit(255);
        else principal.launch(opciones);
        // crear toggle para ventana principal
    }//GEN-LAST:event_btnJugarActionPerformed

    private void txtVerticalComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtVerticalComponentMoved
        sldVertical.setValue(Integer.parseInt(txtVertical.getText()));
    }//GEN-LAST:event_txtVerticalComponentMoved

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrePartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JRadioButton bttClásico;
    private javax.swing.JRadioButton bttExperimental;
    private javax.swing.JCheckBox chkCustomSizes;
    private javax.swing.ButtonGroup grpModo;
    private javax.swing.JSlider sldHorizontal;
    private javax.swing.JSlider sldVertical;
    private javax.swing.JTextField txtHorizontal;
    private javax.swing.JTextField txtVertical;
    // End of variables declaration//GEN-END:variables
}
