package gui;
import game.LauncherRF;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import obj.Settings;
import util.Dialog;
import handler.FileWS;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;
import util.Graphic;


public class PrePartida extends javax.swing.JFrame {
    
    private Settings op;
    private LauncherRF principal;
    private Avanzadas avanzadas;

    /**
     * Creates new form PrePartida
     */
    private PrePartida() {
        initComponents();
        btnJugar.requestFocus(); // permite comenzar la partida al darle enter nada más iniciar.
    }
    
    public PrePartida(LauncherRF p) {
        this();
        principal = p;
        avanzadas = new Avanzadas(this);
        
        // las opciones por defecto son: tamaño 5x5, modo experimental.
        op = new Settings(5, 5, true);
        avanzadas.readValues();
        File defaultSettings = new File("default.sto");
        if(defaultSettings.exists()) {
            openSettingsFile(defaultSettings);
            System.out.println("Cargado archivo de opciones por defecto.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpModo = new javax.swing.ButtonGroup();
        flcOpen = new javax.swing.JFileChooser();
        flcSave = new javax.swing.JFileChooser();
        sldVertical = new javax.swing.JSlider();
        sldHorizontal = new javax.swing.JSlider();
        txtHorizontal = new javax.swing.JTextField();
        txtVertical = new javax.swing.JTextField();
        chkCustomSizes = new javax.swing.JCheckBox();
        btnExperimental = new javax.swing.JRadioButton();
        btnClásico = new javax.swing.JRadioButton();
        btnJugar = new javax.swing.JButton();
        bttAvanzadas = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnDarkMode = new javax.swing.JToggleButton();

        flcOpen.setDialogTitle("SumaTres - Cargar archivo de opciones");

        flcSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        flcSave.setCurrentDirectory(new java.io.File("/home/under/."));
        flcSave.setDialogTitle("SumaTres - Guardar opciones a archivo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SumaTres - Prepartida");
        setName("Prepartida"); // NOI18N
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        sldVertical.setMaximum(12);
        sldVertical.setMinimum(3);
        sldVertical.setOrientation(javax.swing.JSlider.VERTICAL);
        sldVertical.setValue(5);
        sldVertical.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerticalStateChanged(evt);
            }
        });

        sldHorizontal.setMaximum(12);
        sldHorizontal.setMinimum(3);
        sldHorizontal.setValue(5);
        sldHorizontal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldHorizontalChanged(evt);
            }
        });

        txtHorizontal.setEditable(false);
        txtHorizontal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHorizontal.setText("5");
        txtHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorizontalActionPerformed(evt);
            }
        });

        txtVertical.setEditable(false);
        txtVertical.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtVertical.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVertical.setText("5");
        txtVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerticalActionPerformed(evt);
            }
        });

        chkCustomSizes.setText("Tamaño personalizado");
        chkCustomSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomSizesToggled(evt);
            }
        });

        grpModo.add(btnExperimental);
        btnExperimental.setSelected(true);
        btnExperimental.setText("Modo experimental");
        btnExperimental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExperimentalActionPerformed(evt);
            }
        });

        grpModo.add(btnClásico);
        btnClásico.setText("Modo clásico");
        btnClásico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClásicoActionPerformed(evt);
            }
        });

        btnJugar.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        bttAvanzadas.setText("Avanzadas");
        bttAvanzadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAvanzadasActionPerformed(evt);
            }
        });

        btnSave.setText("📁");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnOpen.setText("📂");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnDarkMode.setText("🌙");
        btnDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarkModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(sldVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCustomSizes)
                            .addComponent(btnClásico)
                            .addComponent(btnExperimental)
                            .addComponent(btnJugar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sldHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtVertical, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnDarkMode)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpen)
                                .addGap(18, 18, 18)
                                .addComponent(bttAvanzadas)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttAvanzadas)
                    .addComponent(btnSave)
                    .addComponent(btnOpen)
                    .addComponent(btnDarkMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnJugar)
                        .addGap(18, 18, 18)
                        .addComponent(btnClásico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExperimental)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCustomSizes)
                        .addGap(6, 6, 6))
                    .addComponent(sldVertical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCustomSizesToggled(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomSizesToggled
        txtHorizontal.setEditable(chkCustomSizes.isSelected());
        txtVertical.setEditable(chkCustomSizes.isSelected());
        sldVertical.setEnabled(!chkCustomSizes.isSelected());
        sldHorizontal.setEnabled(!chkCustomSizes.isSelected());
    }//GEN-LAST:event_chkCustomSizesToggled

    private void sldHorizontalChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldHorizontalChanged
        txtHorizontal.setText(String.format("%s", sldHorizontal.getValue()));
        op.setSizey(sldHorizontal.getValue());
    }//GEN-LAST:event_sldHorizontalChanged

    private void sldVerticalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerticalStateChanged
        txtVertical.setText(String.format("%s", sldVertical.getValue()));
        op.setSizex(sldVertical.getValue());
    }//GEN-LAST:event_sldVerticalStateChanged

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        this.setVisible(false);
        if(principal == null) System.exit(255);
        else principal.launch(op);
        avanzadas.setVisible(false);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnClásicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClásicoActionPerformed
        op = new Settings(op.getX(), op.getY(), false);
        avanzadas.readValues();
    }//GEN-LAST:event_btnClásicoActionPerformed

    private void btnExperimentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExperimentalActionPerformed
        op = new Settings(op.getX(), op.getY(), true);
        avanzadas.readValues();
    }//GEN-LAST:event_btnExperimentalActionPerformed

    private void txtVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerticalActionPerformed
        try {
            int val = Integer.parseInt(txtVertical.getText());
            if(val > 20) {
                val = 20;
                txtVertical.setText("20");
            } else if (val < 2) {
                val = 2;
                txtVertical.setText("2");
            }
            
            op.setSizex(val);
        } catch(NumberFormatException ex) {
            Dialog.showError("Este campo solo admite valores naturales.");
            txtVertical.setText(String.valueOf(op.getX()));
        }
    }//GEN-LAST:event_txtVerticalActionPerformed

    private void txtHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorizontalActionPerformed
        try {
            int val = Integer.parseInt(txtHorizontal.getText());
            if(val > 20) {
                val = 20;
                txtHorizontal.setText("20");
            } else if(val < 2) {
                val = 2;
                txtHorizontal.setText("2");
            }
            op.setSizey(val);
        } catch(NumberFormatException ex) {
            Dialog.showError("Este campo solo admite valores naturales.");
            txtHorizontal.setText(String.format("%d", op.getY()));
        }
    }//GEN-LAST:event_txtHorizontalActionPerformed

    private void bttAvanzadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAvanzadasActionPerformed
        avanzadas.setVisible(true);
    }//GEN-LAST:event_bttAvanzadasActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser jfcOpen = new JFileChooser();
        jfcOpen.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfcOpen.setDialogTitle("Cargar archivo de opciones");
        jfcOpen.setMultiSelectionEnabled(false);
        jfcOpen.setFileFilter(new FileNameExtensionFilter("Opciones de partida de SumaTres (.sto)", "sto"));
        int res = jfcOpen.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION) {
            openSettingsFile(jfcOpen.getSelectedFile());
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    /**
     * Carga las opciones desde un archivo de opciones.
     * Para ello, utiliza el constructor de la clase opciones por defecto,
     * que se encarga de asignar y comprobarlo todo. <p>
     * Es importante que se actualicen la ventana de opciones avanzadas mediante
     * <code> readValues() </code> y el estado del botón de modo oscuro, <code>
     * btnDarkMode </code>, para mantenerlo sincronizado con el estado del modo
     * oscuro.
     * 
     * @param f Objeto de tipo archivo que supuestamente contiene opciones. Debe
     *          de estar construido mediante el método <code>toString()</code> de
     *          la clase.
     */
    private void openSettingsFile(File f) {
        try {
            op = new Settings(Files.readString(f.toPath()));
            sldHorizontal.setValue(op.getX());
            sldVertical.setValue(op.getY());
            btnExperimental.setSelected(op.isExperimental());
            txtVertical.setText(String.format("%d", op.getY()));
            txtHorizontal.setText(String.format("%d", op.getX()));
            avanzadas.readValues();
            btnDarkMode.setSelected(true);
            checkDarkMode();
        } catch (IOException ex) {Dialog.showError(ex);}
    }
    
    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser jfcSave = new JFileChooser();
        jfcSave.setDialogTitle("Guardar archivo de opciones");
        jfcSave.setFileFilter(new FileNameExtensionFilter("Opciones de partida de SumaTres (.sto)", "sto"));
        int res = jfcSave.showSaveDialog(null);
        if(res == JFileChooser.APPROVE_OPTION) {
            try {
                FileWS.write(op.toString(), new File(jfcSave.getSelectedFile().getAbsolutePath()));
            } catch (Exception ex) {Dialog.showError(ex);}
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarkModeActionPerformed
        op.toggleDarkMode();
        checkDarkMode();
    }//GEN-LAST:event_btnDarkModeActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) System.exit(0);
    }//GEN-LAST:event_formKeyPressed

    /**
     * Método que comprueba el estado del modo oscuro actual a través del botón
     * de modo oscuro. En caso de estar activado, se accede al método <code>
     * toggleDarkMode() </code> en la ventana principal y se actualizan las
     * ventanas de este nivel. <p> <b> NO cambia el booleano <code>darkModeEnabled
     * </code> en las opciones! </b>
     */
    private void checkDarkMode() {
        principal.toggleDarkMode(op.isDarkModeEnabled());
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(avanzadas);
    }
    
    public Settings getSettings() {return this.op;}
    public void setSettings(Settings op) {this.op = op;}
    public void setExperimental() {
        setSettings(new Settings(op.getX(), op.getY(), true));
        btnExperimental.setSelected(true);
    }
    public void setClassic() {
        setSettings(new Settings(op.getX(), op.getY(), false));
        btnClásico.setSelected(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrePartida().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnClásico;
    private javax.swing.JToggleButton btnDarkMode;
    private javax.swing.JRadioButton btnExperimental;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton bttAvanzadas;
    private javax.swing.JCheckBox chkCustomSizes;
    private javax.swing.JFileChooser flcOpen;
    private javax.swing.JFileChooser flcSave;
    private javax.swing.ButtonGroup grpModo;
    private javax.swing.JSlider sldHorizontal;
    private javax.swing.JSlider sldVertical;
    private javax.swing.JTextField txtHorizontal;
    private javax.swing.JTextField txtVertical;
    // End of variables declaration//GEN-END:variables
}
